[alias]
lint = "clippy --all-targets --all-features -- -D warnings"
lint-app = "clippy --lib --bins --all-features -- -D warnings"
lint-pedantic = "clippy --all-targets --all-features -- -D warnings -D clippy::pedantic"
test-all = "test --all-features"
doc-all = "doc --all-features --no-deps"
deny-all = "deny check advisories licenses sources"
